"""delivered column added to staff

Revision ID: 0e25a8dfc6d6
Revises: 00eff1739a5c
Create Date: 2018-04-24 14:30:59.436260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e25a8dfc6d6'
down_revision = '00eff1739a5c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('delivered', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'delivered')
    # ### end Alembic commands ###
