"""Added staff_name column to replace staffname

Revision ID: 440ada6979b9
Revises: 1d93d2b8f0e5
Create Date: 2018-11-03 15:15:13.417935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '440ada6979b9'
down_revision = '1d93d2b8f0e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_staff_staff_name'), 'staff', ['staff_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_staff_name'), table_name='staff')
    # ### end Alembic commands ###
