"""admin table, password column dropped

Revision ID: 523de11f2d5f
Revises: a2db87d3b2fb
Create Date: 2018-12-31 18:45:24.181872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '523de11f2d5f'
down_revision = 'a2db87d3b2fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("admin") as batch_op:
        batch_op.drop_column('password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('password', sa.VARCHAR(length=128), nullable=True))
    # ### end Alembic commands ###
