"""Added risk_score column to replace confidence

Revision ID: 715d63f3b96c
Revises: b4a1109001bd
Create Date: 2018-12-20 19:31:55.192863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '715d63f3b96c'
down_revision = 'b4a1109001bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('risk_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'risk_score')
    # ### end Alembic commands ###
