"""last_sent column added

Revision ID: c6f1f0d91d7e
Revises: f68131da43fb
Create Date: 2018-12-24 19:37:30.122210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6f1f0d91d7e'
down_revision = 'f68131da43fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('last_sent', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'last_sent')
    # ### end Alembic commands ###
