"""admin table, password_hash column added to replace password column

Revision ID: e0e3706fbf9b
Revises: 523de11f2d5f
Create Date: 2018-12-31 18:47:14.761559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e0e3706fbf9b'
down_revision = '523de11f2d5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('admin', sa.Column('password_hash', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin', 'password_hash')
    # ### end Alembic commands ###
